# Generated by Django 3.1.2 on 2022-09-20 13:25
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 13, 25, 48, 884389, tzinfo=utc), verbose_name='date end'),
        ),
    ]